# This file contains values from Cookiecutter

default_context:
  project_name: "rundry"
  project_description: "Estimate when a home heating oil tank will run dry."
  organization: "Robert Cohn"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "rscohn2"
  email: "rscohn2@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
